<?php
function nbainfo_forum_permission() {
  return array(
    'promote comment to frontpage' => array(
      'title' => t('Promote comment to frontpage'),
      'description' => t('Promote comment to frontpage.'),
    ),
  );
}
function nbainfo_forum_menu() {
  $items['comment/%/promote_to_front'] = array(
    'title' => 'Promote to front page',
    'page callback' => 'nbainfo_forum_promote_to_frontpage',
    'page arguments' => array(1),
    'access arguments' => array('promote comment to frontpage'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
/**
* AJAXIFY using http://www.computerminds.co.uk/drupal-code/make-link-use-ajax-drupal-7-its-easy
*
*/
function nbainfo_forum_promote_to_frontpage($comment_id) {
  $comment_object = comment_load($comment_id, TRUE);
  $comment_object->field_promote_to_frontpage['und'][0]=57; //YES
  $entity_instance->save();
}
?>
